// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znjiffshrxzptkqzjfzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuamlmZnNocnh6cHRrcXpqZnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDc2MzIsImV4cCI6MjA2MzU4MzYzMn0.z8C2jt8amTXwMbAdfKP-n5CKtZuGKgkXQjQgvdcJ3Uw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);